### ISSUE TITLE
tape browser URL can not be opened once

### ISSUE THREAD

**Issue by rizar** [ServiceNow/TapeAgents#94]
when I try to reopen to the tape browser URL, I get this:

```
Traceback (most recent call last):
  File "/home/toolkit/.conda/envs/tapeagents/lib/python3.10/site-packages/gradio/queueing.py", line 536, in process_events
    response = await route_utils.call_process_api(
  File "/home/toolkit/.conda/envs/tapeagents/lib/python3.10/site-packages/gradio/route_utils.py", line 276, in call_process_api
    output = await app.get_blocks().process_api(
  File "/home/toolkit/.conda/envs/tapeagents/lib/python3.10/site-packages/gradio/blocks.py", line 1923, in process_api
    result = await self.call_function(
  File "/home/toolkit/.conda/envs/tapeagents/lib/python3.10/site-packages/gradio/blocks.py", line 1508, in call_function
    prediction = await anyio.to_thread.run_sync(  # type: ignore
  File "/home/toolkit/.conda/envs/tapeagents/lib/python3.10/site-packages/anyio/to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "/home/toolkit/.conda/envs/tapeagents/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 2441, in run_sync_in_worker_thread
    return await future
  File "/home/toolkit/.conda/envs/tapeagents/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 943, in run
    result = context.run(func, *args)
  File "/home/toolkit/.conda/envs/tapeagents/lib/python3.10/site-packages/gradio/utils.py", line 818, in wrapper
    response = f(*args, **kwargs)
  File "/home/toolkit/dist/TapeAgents/tapeagents/tape_browser.py", line 184, in get_request_params
    selected_file = self.files[0]
IndexError: list index out of range
```

**Comment by ollmer** [comment]
Please share the command that you're using to run a browser and the folder with tapes
